name: test

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: List Files in workspace
        if: always()
        run: |
          ls -R;
      - name: Get Test Results history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Create Test Results History
        uses: krishnaaSundaram-QaStack-1989/playwright_baseframework

        with:
          test_results: automation-report
          gh_pages: gh-pages
          results_history: results-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: krishnaaSundaram-QaStack-1989/playwright_baseframework
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_branch: gh-pages
          publish_dir: results-history
          keep_files: true
